# Dependencies
gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            "Pete Peterson"
tagline:          "Pete Peterson Music"
description:      ""
url:              http://petepetersonmusic.com
baseurl:          /

author:
  name:           "Pete Peterson"
  url:            https://twitter.com/petepppeterson

paginate:         5

github:
  repo:           https://github.com/petepm/petepm.github.io
